/// Flutter icons Eb
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Eb
///      fonts:
///       - asset: fonts/Eb.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Eb {
  Eb._();

  static const _kFontFam = 'Eb';
  static const String _kFontPkg = null;

  static const IconData uniE900 = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE901 = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE902 = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE903 = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE904 = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE905 = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE906 = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE907 = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE908 = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE909 = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90A = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90B = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90C = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90D = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90E = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE90F = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE910 = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE911 = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE912 = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE913 = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE914 = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE915 = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE916 = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE917 = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE918 = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE919 = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91A = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91B = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91C = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91D = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91E = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE91F = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE920 = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE921 = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE922 = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE923 = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE924 = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE925 = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE926 = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE927 = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE928 = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE929 = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92A = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92B = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92C = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92D = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92E = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE92F = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE930 = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE931 = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE932 = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE933 = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE934 = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE935 = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE936 = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE937 = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE938 = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE939 = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93A = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93B = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93C = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93D = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93E = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE93F = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE940 = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE941 = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE942 = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE943 = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE944 = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE945 = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE946 = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE947 = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE948 = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE949 = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94A = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94B = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94C = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94D = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94E = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94F = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE950 = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE951 = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE952 = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE953 = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE954 = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE955 = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE956 = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE957 = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE958 = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE959 = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95A = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95B = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95C = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95D = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95E = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE95F = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE960 = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE961 = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE962 = IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE963 = IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE964 = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE965 = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE966 = IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE967 = IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE968 = IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE969 = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE96A = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE96B = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE96C = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE96D = IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE96E = IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Home = IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE970 = IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE971 = IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE972 = IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE973 = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE974 = IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE975 = IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE976 = IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE977 = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE978 = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE979 = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97A = IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97B = IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97C = IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97D = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97E = IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE97F = IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE980 = IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE981 = IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE982 = IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE983 = IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE984 = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE985 = IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE986 = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData livebet = IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE988 = IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE989 = IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE98A = IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE98B = IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE98C = IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE98D = IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE98E = IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Live = IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE990 = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minigames = IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE992 = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE993 = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocker = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE995 = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposals = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE997 = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE998 = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE999 = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jeckpot = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Sport = IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE99D = IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE99E = IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE99F = IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boardgame = IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE9A1 = IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tvgames = IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virtualgames = IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE9A4 = IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
